# Generated by Django 4.2.5 on 2023-09-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0002_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='seller_email',
            field=models.CharField(default='johndoe@email.com', max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='seller_name',
            field=models.CharField(default='john doe', max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='seller_phone_number',
            field=models.IntegerField(default=12345678),
        ),
    ]
